description: Specifies information about your integration, which is useful for debugging.
properties:
  shop:
    description: The name of the application/ecommerce.
    type: string
    example: "My self-made integration"
  plugin_version:
    description: The version of the plugin.
    type: string
    example: "1.0.0"
  shop_version: 
    description: The version of the ecommerce webshop you use.
    type: string
    example: ""
  partner: 
    description: The name of the third party that developed the ecommerce webshop.
    type: string
  shop_root_url:
    description: The root/base URL of the ecommerce webshop.
    type: string
    example: "https://www.my-ecommerce.com"