properties:
  name:
    maxLength: 120
    type: string
  notification_url:
    $ref: 'Webhook.yaml'
  price_from:
    $ref: 'PriceFrom.yaml'
  price_till:
    $ref: 'PriceTill.yaml'
  support_email:
    $ref: 'SupportEmail.yaml'
  support_phone:
    $ref: 'SupportPhone.yaml'
  url:
    $ref: 'URL.yaml'
required:
  - name
  - url
type: object
